[General]
network = src.man
sim-time-limit = 10s
description = "Manual FRER 5 Paths - Loop Free Configuration"

# -------------------------------------------------
# 1. General settings
# -------------------------------------------------
*.macForwardingTableConfigurator.typename = ""
*.*.eth[*].bitrate = 100Mbps
**.throughput.interval = 10ms
*.*.hasStreamRedundancy = true
seed-set=29
# -------------------------------------------------
# 2. Advanced Failure Scenario 
# -------------------------------------------------
*.scenarioManager.script = xml("<scenario> \
  <at t='2s'> \
    <disconnect src-module='s1' dest-module='s2c'/> \
  </at> \
  <at t='6s'> \
    <disconnect src-module='s1' dest-module='s2b'/> \
  </at> \
</scenario>")

# -------------------------------------------------
# 3. Applications 
# -------------------------------------------------
*.source.numApps = 1
*.source.app[0].typename = "UdpSourceApp"
*.source.app[0].io.destAddress = "destination"
*.source.app[0].io.destPort = 1000
*.source.app[0].source.packetLength = 1200B
*.source.app[0].source.productionInterval = truncnormal(100us,50us)

*.destination.numApps = 1
*.destination.app[0].typename = "UdpSinkApp"
*.destination.app[0].io.localPort = 1000
*.destination.eth[*].address = "0A-AA-12-34-56-78"

# -------------------------------------------------
# 4.Source
# -------------------------------------------------
*.source.bridging.streamIdentifier.identifier.mapping = [{packetFilter: "*", stream: "s1", sequenceNumbering: true}]
*.source.bridging.streamCoder.encoder.mapping = [{stream: "s1", vlan: 1}]

# -------------------------------------------------
# 5.s1 
# -------------------------------------------------
*.s1.bridging.streamRelay.typename = "StreamRelayLayer"
*.s1.bridging.streamCoder.typename = "StreamCoderLayer"
*.s1.ieee8021q.qTagHeaderChecker.vlanIdFilter = [1]

*.s1.bridging.streamCoder.decoder.mapping = [{interface: "eth0", vlan: 1, stream: "s1"}]
*.s1.bridging.streamRelay.merger.mapping = {s1: "s1"}
*.s1.bridging.streamRelay.splitter.mapping = {s1: ["s2a", "s2b", "s2c"]}

*.s1.bridging.streamCoder.encoder.mapping = [{stream: "s2a", vlan: 1}, \
                                             {stream: "s2b", vlan: 2}, \
                                             {stream: "s2c", vlan: 3}]

*.s1.macTable.forwardingTable = [{address: "destination", vlan: 1, interface: "eth1"}, \
                                 {address: "destination", vlan: 2, interface: "eth2"}, \
                                 {address: "destination", vlan: 3, interface: "eth3"}]

# -------------------------------------------------
# 6.s2a 
# -------------------------------------------------
*.s2a.bridging.streamRelay.typename = "StreamRelayLayer"
*.s2a.bridging.streamCoder.typename = "StreamCoderLayer"
*.s2a.ieee8021q.qTagHeaderChecker.vlanIdFilter = [1, 2]

*.s2a.bridging.streamCoder.decoder.mapping = [{interface: "eth0", vlan: 1, stream: "s2a"}, \
                                              {interface: "eth2", vlan: 2, stream: "s2b-cross"}]

*.s2a.bridging.streamRelay.merger.mapping = {s2a: "s3a_stream", "s2b-cross": "s3a_stream"}
*.s2a.bridging.streamRelay.splitter.mapping = {s3a_stream: ["s3a_stream", "s2a-cross"]}

*.s2a.bridging.streamCoder.encoder.mapping = [{stream: "s3a_stream", vlan: 1}, \
                                              {stream: "s2a-cross", vlan: 2}]

*.s2a.macTable.forwardingTable = [{address: "destination", vlan: 1, interface: "eth1"}, \
                                  {address: "destination", vlan: 2, interface: "eth2"}]

# -------------------------------------------------
# 7.s2b 
# -------------------------------------------------
*.s2b.bridging.streamRelay.typename = "StreamRelayLayer"
*.s2b.bridging.streamCoder.typename = "StreamCoderLayer"
*.s2b.ieee8021q.qTagHeaderChecker.vlanIdFilter = [1, 2]

*.s2b.bridging.streamCoder.decoder.mapping = [{interface: "eth0", vlan: 2, stream: "s2b"}, \
                                              {interface: "eth2", vlan: 2, stream: "s2a-cross"}]

*.s2b.bridging.streamRelay.merger.mapping = {s2b: "s3b_stream", "s2a-cross": "s3b_stream"}
*.s2b.bridging.streamRelay.splitter.mapping = {s3b_stream: ["s3b_stream", "s2b-cross"]}

*.s2b.bridging.streamCoder.encoder.mapping = [{stream: "s3b_stream", vlan: 1}, \
                                              {stream: "s2b-cross", vlan: 2}]

*.s2b.macTable.forwardingTable = [{address: "destination", vlan: 1, interface: "eth1"}, \
                                  {address: "destination", vlan: 2, interface: "eth2"}]

# -------------------------------------------------
# 8.s2c 
# -------------------------------------------------
*.s2c.macTable.forwardingTable = [{address: "destination", vlan: 3, interface: "eth1"}]

# -------------------------------------------------
# 9.(s3a, s3b, s3c)
# -------------------------------------------------
*.s3a.macTable.forwardingTable = [{address: "destination", vlan: 1, interface: "eth1"}]
*.s3b.macTable.forwardingTable = [{address: "destination", vlan: 1, interface: "eth1"}]
*.s3c.macTable.forwardingTable = [{address: "destination", vlan: 3, interface: "eth1"}]

# -------------------------------------------------
# 10. (Destination Decoder & Merger)
# -------------------------------------------------
*.*.bridging.streamRelay.typename = "StreamRelayLayer"
*.*.bridging.streamCoder.typename = "StreamCoderLayer"

*.destination.ieee8021q.qTagHeaderChecker.vlanIdFilter = [1, 3]
*.destination.bridging.streamCoder.decoder.mapping = [{interface: "eth0", vlan: 1, stream: "s3a_stream"}, \
                                                      {interface: "eth1", vlan: 1, stream: "s3b_stream"}, \
                                                      {interface: "eth2", vlan: 3, stream: "s2c_stream"}]

*.destination.bridging.streamRelay.merger.mapping = {s3a_stream: "", s3b_stream: "", s2c_stream: ""}

# -------------------------------------------------
# 11.Statistics 
# -------------------------------------------------
output-scalar-file = ${resultdir}/${configname}-${repetition}.sca
output-vector-file = ${resultdir}/${configname}-${repetition}.vec

**.app[0].sink.endToEndDelay:vector.record = true
**.app[0].sink.throughput:vector.record = true
**.app[0].source.packetSent:count.record = true
**.app[0].sink.packetReceived:count.record = true

**.bridging.streamRelay.merger.pushedPacket:count.record = true
**.bridging.streamRelay.merger.passedPacket:count.record = true

**.eth[*].macLayer.queue.packetDrop:count.record = true
**.eth[*].macLayer.queue.queueLength:vector.record = true
**.memoryUsage:vector.record = true

# -------------------------------------------------
# 12.Visualization
# -------------------------------------------------
*.visualizer.infoVisualizer.modules = "*.source.app[0].source or *.destination.app[0].sink"