[General]
network = src.MergedFRERNetwork
sim-time-limit = 10.5s
description = "Drain experiment: UdpBasicApp with stopTime=10s"

*.macForwardingTableConfigurator.typename = ""
*.*.eth[*].bitrate = 100Mbps
*.*.hasStreamRedundancy = true
seed-set = 0

# -------------------------------------------------
# 2. Advanced Failure Scenario
# -------------------------------------------------
*.scenarioManager.script = xml("<scenario> \
  <at t='2s'> \
    <disconnect src-module='s1' dest-module='s2c'/> \
  </at> \
  <at t='6s'> \
    <disconnect src-module='s1' dest-module='s2b'/> \
  </at> \
</scenario>")

# -------------------------------------------------
# 3. Applications (UdpBasicApp)
# -------------------------------------------------
*.source.numApps = 1
*.source.app[0].typename = "UdpBasicApp"
*.source.app[0].destAddresses = "destination"
*.source.app[0].destPort = 1000
*.source.app[0].messageLength = 1200B
*.source.app[0].sendInterval = truncnormal(100us,50us)
*.source.app[0].startTime = 0s
*.source.app[0].stopTime = 10s    # 

*.destination.numApps = 1
*.destination.app[0].typename = "UdpSinkApp"
*.destination.app[0].io.localPort = 1000
*.destination.eth[*].address = "0A-AA-12-34-56-78"
# -------------------------------------------------
# 4. Automatic FRER configuration 
# -------------------------------------------------
*.*.bridging.streamRelay.typename = "StreamRelayLayer"
*.*.bridging.streamCoder.typename = "StreamCoderLayer"

*.streamRedundancyConfigurator.typename = "StreamRedundancyConfigurator"
*.streamRedundancyConfigurator.configuration = [{name: "S1", packetFilter: "*", source: "source", destination: "destination", \
                                                 trees: [[["source", "s1", "s2a", "s3a", "destination"]], \
                                                         [["source", "s1", "s2b", "s3b", "destination"]], \
                                                         [["source", "s1","s2a", "s2b", "s3b", "destination"]],\
                                                         [["source", "s1", "s2b","s2a", "s3a", "destination"]], \
                                                         [["source", "s1", "s2c", "s3c", "destination"]]]}]

# -------------------------------------------------
# 5. Statistics
# -------------------------------------------------
output-scalar-file = ${resultdir}/${configname}-${repetition}.sca
output-vector-file = ${resultdir}/${configname}-${repetition}.vec

# UdpBasicApp
**.source.app[0].packetSent:count.record = true

# UdpSinkApp
**.destination.app[0].sink.packetReceived:count.record = true
**.destination.app[0].sink.endToEndDelay:vector.record = true

# 
**.destination.bridging.streamRelay.merger.passedPacket:count.record = true
**.eth[*].macLayer.queue.packetDrop:count.record = true

# -------------------------------------------------
# 6. Visualization
# -------------------------------------------------
*.visualizer.infoVisualizer.modules = "*.source.app[0] or *.destination.app[0].sink"
*.visualizer.streamRedundancyConfigurationVisualizer.displayTrees = true